config/routes.rb
Maintain::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match 'login', to: 'sessions#new', via: 'get'
  match 'logout', to: 'sessions#destroy', via: 'delete'

  resources :users
  match 'signup', to: 'users#new', via: 'get'

  get "static/about"

  resources :vendors

  resources :hwservicepositions
  match 'hwservicepositions/:id/addtoservice' => 'hwservicepositions#addtoservice', :via => :get, :as => 'addtoservice_hwserviceposition'

  resources :servicelevels

  resources :hwservices do
    resources :hwservicepositions
  end 

  resources :hardwares

  root :to => 'sessions#new'

end

app/models/servicelevel.rb
class Servicelevel < ActiveRecord::Base
  attr_accessible :level, :long_desc, :short_desc

  has_many :hwservicepositions
  
  def selectString
    level + " - " + short_desc
  end
  
end

app/controllers/servicelevels_controller.rb
class ServicelevelsController < ApplicationController
  
  before_filter :verify_session, :only => [:index, :show, :edit, :destroy, :create, :update, :new]

  def verify_session
    unless session[:user_id]
      flash[:danger] = "You must log in to use this feature!"
      redirect_to :controller => 'sessions', :action => 'new'
    end
  end  
 
  # GET /servicelevels
  # GET /servicelevels.json
  def index
    @servicelevels = Servicelevel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servicelevels }
    end
  end

  # GET /servicelevels/1
  # GET /servicelevels/1.json
  def show
    @servicelevel = Servicelevel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @servicelevel }
    end
  end

  # GET /servicelevels/new
  # GET /servicelevels/new.json
  def new
    @servicelevel = Servicelevel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @servicelevel }
    end
  end

  # GET /servicelevels/1/edit
  def edit
    @servicelevel = Servicelevel.find(params[:id])
  end

  # POST /servicelevels
  # POST /servicelevels.json
  def create
    @servicelevel = Servicelevel.new(params[:servicelevel])

    respond_to do |format|
      if @servicelevel.save
#        format.html { redirect_to @servicelevel, notice: 'Servicelevel was successfully created.' }
        format.html { redirect_to servicelevels_url }
        format.json { render json: @servicelevel, status: :created, location: @servicelevel }
      else
        format.html { render action: "new" }
        format.json { render json: @servicelevel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servicelevels/1
  # PUT /servicelevels/1.json
  def update
    @servicelevel = Servicelevel.find(params[:id])

    respond_to do |format|
      if @servicelevel.update_attributes(params[:servicelevel])
#        format.html { redirect_to @servicelevel, notice: 'Servicelevel was successfully updated.' }
        format.html { redirect_to servicelevels_url }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @servicelevel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicelevels/1
  # DELETE /servicelevels/1.json
  def destroy
    @servicelevel = Servicelevel.find(params[:id])
    @servicelevel.destroy

    respond_to do |format|
      format.html { redirect_to servicelevels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/servicelevels_helper.rb
module ServicelevelsHelper
end

app/views/servicelevels/_form.html.erb
<%= form_for(@servicelevel, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @servicelevel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servicelevel.errors.count, "error") %> prohibited this servicelevel from being saved:</h2>

      <ul>
      <% @servicelevel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label "Level Code",  :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :level, :class => 'input-small' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :short_desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :short_desc, :class => 'input-xlarge' %>
    </div>  
  </div>

  <div class="control-group">
    <%= f.label :long_desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :long_desc, :rows => 7, :class => 'input-xxlarge' %>
    </div>  
  </div>

  <div class="form-actions">
    <%= f.submit "Save", :class => 'btn btn-primary' %>
    <%=link_to 'Cancel', servicelevels_path, :class => 'btn' %>
  </div>

<% end %>

app/views/servicelevels/edit.html.erb
<legend>Edit Servicelevel</legend>

<%= render 'form' %>

<!--
<%= link_to 'Show', @servicelevel %> |
<%= link_to 'Back', servicelevels_path %>
-->

app/views/servicelevels/index.html.erb
<h1>Servicelevels</h1>

<%= link_to 'New Servicelevel', new_servicelevel_path %>
<p />

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Level Code</th>
    <th>Short desc</th>
    <th>Long desc</th>
    <th colspan="2">Actions</th>
  </tr>

<% @servicelevels.each do |servicelevel| %>
  <tr>
    <td><%= servicelevel.level %></td>
    <td><%= servicelevel.short_desc %></td>
    <td><%= servicelevel.long_desc %></td>
    <td><%= link_to 'Edit', edit_servicelevel_path(servicelevel) %></td>
    <td><%= link_to 'Delete', servicelevel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/servicelevels/new.html.erb
<legend>New Servicelevel</legend>

<%= render 'form' %>

<!--
<%= link_to 'Back', servicelevels_path %>
-->

app/views/servicelevels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Level:</b>
  <%= @servicelevel.level %>
</p>

<p>
  <b>Short desc:</b>
  <%= @servicelevel.short_desc %>
</p>

<p>
  <b>Long desc:</b>
  <%= @servicelevel.long_desc %>
</p>


<%= link_to 'Edit', edit_servicelevel_path(@servicelevel) %> |
<%= link_to 'Back', servicelevels_path %>