config/routes.rb
Maintain::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match 'login', to: 'sessions#new', via: 'get'
  match 'logout', to: 'sessions#destroy', via: 'delete'

  resources :users
  match 'signup', to: 'users#new', via: 'get'

  get "static/about"

  resources :vendors

  resources :hwservicepositions
  match 'hwservicepositions/:id/addtoservice' => 'hwservicepositions#addtoservice', :via => :get, :as => 'addtoservice_hwserviceposition'

  resources :servicelevels

  resources :hwservices do
    resources :hwservicepositions
  end 

  resources :hardwares

  root :to => 'sessions#new'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :location, :name1, :name2, :nationality, :street, :vendor_id, :zip

  validates :name1, presence: true

  has_many :hwservices
  
  def selectString
    vendor_id + " - " + name1 + " " + location
  end
    
 end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  
  before_filter :verify_session, :only => [:index, :show, :edit, :destroy, :create, :update, :new]

  def verify_session
    unless session[:user_id]
      flash[:danger] = "You must log in to use this feature!"
      redirect_to :controller => 'sessions', :action => 'new'
    end
  end  
 
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vendors }
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
#        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.html { redirect_to vendors_url }
        format.json { render json: @vendor, status: :created, location: @vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
#        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.html { redirect_to vendors_url }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label "Vendor Code", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vendor_id, :class => 'text_field' %>
    </div>  
  </div>

  <div class="control-group">
    <%= f.label :name1, :class => 'control-label'  %>
    <div class="controls">
      <%= f.text_field :name1, :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name2, :class => 'control-label'  %>
    <div class="controls">
      <%= f.text_field :name2, :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :street, :class => 'control-label'  %>
    <div class="controls">
      <%= f.text_field :street, :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :zip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zip %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :nationality, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nationality, :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Save", :class => 'btn btn-primary' %>
    <%=link_to 'Cancel', vendors_path, :class => 'btn' %>
  </div>

<% end %>

app/views/vendors/edit.html.erb
<legend>Edit Vendor</legend>

<%= render 'form' %>
<!--
<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>
-->

app/views/vendors/index.html.erb
<h1>Vendors</h1>

<%= link_to 'New Vendor', new_vendor_path %>
<p />

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Vendor</th>
    <th>Name1</th>
    <th>Name2</th>
    <th>Street</th>
    <th>Zip</th>
    <th>Location</th>
    <th>Nationality</th>
    <th colspan="2">Actions</th>
  </tr>

<% @vendors.each do |vendor| %>
  <tr>
    <td><%= vendor.vendor_id %></td>
    <td><%= vendor.name1 %></td>
    <td><%= vendor.name2 %></td>
    <td><%= vendor.street %></td>
    <td><%= vendor.zip %></td>
    <td><%= vendor.location %></td>
    <td><%= vendor.nationality %></td>
    <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
    <td><%= link_to 'Delete', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/vendors/new.html.erb
<legend>New Vendor</legend>

<%= render 'form' %>

<!--
<%= link_to 'Back', vendors_path %>
-->

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vendor:</b>
  <%= @vendor.vendor_id %>
</p>

<p>
  <b>Name1:</b>
  <%= @vendor.name1 %>
</p>

<p>
  <b>Name2:</b>
  <%= @vendor.name2 %>
</p>

<p>
  <b>Street:</b>
  <%= @vendor.street %>
</p>

<p>
  <b>Zip:</b>
  <%= @vendor.zip %>
</p>

<p>
  <b>Location:</b>
  <%= @vendor.location %>
</p>

<p>
  <b>Nationality:</b>
  <%= @vendor.nationality %>
</p>


<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>