config/routes.rb
Maintain::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match 'login', to: 'sessions#new', via: 'get'
  match 'logout', to: 'sessions#destroy', via: 'delete'

  resources :users
  match 'signup', to: 'users#new', via: 'get'

  get "static/about"

  resources :vendors

  resources :hwservicepositions
  match 'hwservicepositions/:id/addtoservice' => 'hwservicepositions#addtoservice', :via => :get, :as => 'addtoservice_hwserviceposition'

  resources :servicelevels

  resources :hwservices do
    resources :hwservicepositions
  end 

  resources :hardwares

  root :to => 'sessions#new'

end

app/models/hwservice.rb
class Hwservice < ActiveRecord::Base
  attr_accessible :issue_date, :ordernr, :period_of_notice, :renewal_auto, :startdate, :subordernr, :vendor_id, :validity, :desc

  has_many :hwservicepositions, :dependent => :destroy
  belongs_to :vendor

  def vendor_ident
  	if vendor.nil?
  	  ""	
  	else 
      vendor.vendor_id
    end 
  end
  
  def vendor_name1
  	if vendor.nil?
      ""
    else
      vendor.name1
    end
  end
  
  def vendor_location
  	if vendor.nil?
      ""
    else   
      vendor.location
    end
  end
  
  def validuntil
  	if startdate.nil? || validity.nil?
  	  ""
  	else  
      startdate + validity.months - 1.days
    end 
  end 

end

app/controllers/hwservices_controller.rb
class HwservicesController < ApplicationController
  
  before_filter :verify_session, :only => [:index, :show, :edit, :destroy, :create, :update, :new]

  def verify_session
    unless session[:user_id]
      flash[:danger] = "You must log in to use this feature!"
      redirect_to :controller => 'sessions', :action => 'new'
    end
  end  
 
  # GET /hwservices
  # GET /hwservices.json
  def index
    @hwservices = Hwservice.find(:all, :order => 'startdate')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hwservices }
    end
  end

  # GET /Hwservices/1
  # GET /Hwservices/1.json
  def show
    @hwservice = Hwservice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hwservice }
    end
  end

  # GET /Hwservices/new
  # GET /Hwservices/new.json
  def new
    @hwservice = Hwservice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hwservice }
    end
  end

  # GET /Hwservices/1/edit
  def edit
    @hwservice = Hwservice.find(params[:id])
  end

  # POST /Hwservices
  # POST /Hwservices.json
  def create
    @hwservice = Hwservice.new(params[:hwservice])

    respond_to do |format|
      if @hwservice.save
        format.html { redirect_to @hwservice, notice: 'Hw service was successfully created.' }
        format.json { render json: @hwservice, status: :created, location: @hwservice }
      else
        format.html { render action: "new" }
        format.json { render json: @hwservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /Hwservices/1
  # PUT /Hwservices/1.json
  def update
    @hwservice = Hwservice.find(params[:id])

    respond_to do |format|
      if @hwservice.update_attributes(params[:hwservice])
        format.html { redirect_to @hwservice, notice: 'Hw service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hwservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Hwservices/1
  # DELETE /Hwservices/1.json
  def destroy
    @hwservice = Hwservice.find(params[:id])
    @hwservice.destroy

    respond_to do |format|
      format.html { redirect_to hwservices_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/hwservices_helper.rb
module HwservicesHelper
end

app/views/hwservices/_form.html.erb
<%= form_for(@hwservice, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @hwservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hwservice.errors.count, "error") %> prohibited this hwservice from being saved:</h2>

      <ul>
      <% @hwservice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group" >
    <%= f.label :ordernr, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ordernr, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :subordernr, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subordernr, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc, :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :startdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :startdate, {}, {:class => 'date-select'}  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :validity, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :validity, :class => 'input-small' %>
      <span class="help-inline">  (Months)</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :vendor_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:hwservice, :vendor_id, Vendor.all, :id, :selectString, {}, {:class=>'input-xxlarge'}) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :issue_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :issue_date, {}, {:class => 'date-select'} %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :period_of_notice, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :period_of_notice, :class => 'input-small' %>
      <span class="help-inline">  (Months)</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :renewal_auto, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :renewal_auto, :class => 'input-small' %>
      <span class="help-inline">  (Months)</span>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Save", :class => 'btn btn-primary' %>
    <% if @hwservice.id.nil? %>
      <%=link_to 'Cancel', hwservices_path, :class => 'btn' %>
    <% else %>
      <%= link_to 'Cancel', hwservice_path(@hwservice), :class => 'btn' %>
    <% end %> 
  </div>

<% end %>

app/views/hwservices/edit.html.erb
<legend>Edit Hardware Maintenance Contract</legend>

<%= render 'form' %>

<!--
<%= link_to 'Back', hwservices_path %>
-->

app/views/hwservices/index.html.erb
<h1>Hardware Maintenance Contracts</h1>

<%= link_to 'New Contract', new_hwservice_path %>
<p />

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Ordernr</th>
    <th>Subordernr</th>
	<th>Description</th>
    <th>Startdate</th>
    <th>Validity</th>
    <th>Valid until</th>
    <th>Vendor</th>
    <th>Actions</th>
  </tr>

<% @hwservices.each do |hwservice| %>
  <tr>
    <td><%= hwservice.ordernr %></td>
    <td><%= hwservice.subordernr %></td>
    <td><%= hwservice.desc %></td>
    <td><%= hwservice.startdate %></td>
    <td style="text-align: right"><%= hwservice.validity %></td>
    <td><%= hwservice.validuntil %></td>
    <td><%= hwservice.vendor_ident + " " + hwservice.vendor_name1%></td>
    <td><%= link_to 'View', hwservice %></td>
<!--    <td><%= link_to 'Edit', edit_hwservice_path(hwservice) %></td>
    <td><%= link_to 'Destroy', hwservice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
	</tr>
<% end %>
</table>

<br />

app/views/hwservices/new.html.erb
<legend>New Hardware Maintenance Contract</legend>

<%= render 'form' %>

<!--
<%= link_to 'Back', hwservices_path %>
-->

app/views/hwservices/show.html.erb
<h1>Hardware Maintenance Contract</h1>
<%= link_to 'Edit', edit_hwservice_path(@hwservice) %>
or
<%= link_to 'Delete', @hwservice, method: :delete, data: { confirm: 'Are you sure?' } %>

<!-- 
<p id="notice"><%= notice %></p>
-->

<dl class="dl-horizontal">
  <dt>Ordernr:</dt>
  <dd><%= @hwservice.ordernr %></dd>
  <dt>Sub-Ordernr:</dt>
  <dd><%= @hwservice.subordernr %></dd>

  <dt>Description:</dt>
  <dd><%= @hwservice.desc %></dd>
  <dt>Startdate:</dt>
  <dd><%= @hwservice.startdate %></dd>
  <dt>Validity:</dt>
  <dd><%= @hwservice.validity %> <small>(Months)</small></dd>
  <dt>Valid until:</dt>
  <dd><%= @hwservice.validuntil %></dd>

  <dt>Vendor:</dt>
  <dd><%= @hwservice.vendor_ident %>, 
  <%= @hwservice.vendor_name1 %>, 
  <%= @hwservice.vendor_location %></dd>
  
  <dt>Issue date:</dt>
  <dd><%= @hwservice.issue_date %></dd>
  <dt>Period of notice:</dt>
  <dd><%= @hwservice.period_of_notice %> <small>(Months)</small></dd>
  <dt>Auto renewal:</b>
  <dd><%= @hwservice.renewal_auto %> <small>(Months)</small></dd>
</dl>

<hr>
<h2>Service Positions</h2>
<%= link_to 'New service position', new_hwservice_hwserviceposition_path(@hwservice) %>

<p />
<table class="table table-striped table-bordered table-condensed">

 <tr>
    <th>Hardware</th>
    <th>Servicelevel</th>
    <th>Start</th>
    <th>End</th>
    <th>Fee €</th>
    <th>Period</th>
    <th colspan="2">Actions</th>
  </tr>
  
<%= render @hwservice.hwservicepositions %>
</table>


<br />