config/routes.rb
Maintain::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match 'login', to: 'sessions#new', via: 'get'
  match 'logout', to: 'sessions#destroy', via: 'delete'

  resources :users
  match 'signup', to: 'users#new', via: 'get'

  get "static/about"

  resources :vendors

  resources :hwservicepositions
  match 'hwservicepositions/:id/addtoservice' => 'hwservicepositions#addtoservice', :via => :get, :as => 'addtoservice_hwserviceposition'

  resources :servicelevels

  resources :hwservices do
    resources :hwservicepositions
  end 

  resources :hardwares

  root :to => 'sessions#new'

end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <div class="row">
    <div class="col-md-12">
      <div class="col-md-8">
        <%= link_to "About", static_about_path %>
	    </div>

    <div class="col-md-4">
      <p class="muted pull-right">
	      <small>© 2013 by Johann Kropf. All rights reserved</small>
	    </p>
    </div>
	</div>

</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">

   <div class="navbar-header">
     <div class="navbar-brand">
       <%= link_to "Maintenance", '#', id: "logo" %>
     </div>
   </div>

   <ul class="nav navbar-nav">

     <% if session[:user_id] %>
	     <li><%= link_to "Contracts", hwservices_path %></li>
		   <li><%= link_to "Vendors", vendors_path %></li>
		   <li><%= link_to "Servicelevels", servicelevels_path %></li>
		   <li><%= link_to "Hardware", hardwares_path %></li>
     <% end %>

     </ul>
       <ul class="nav navbar-nav navbar-right">

         <% if session[:user_id] %>
           <li class="dropdown">  
             <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
             <ul class="dropdown-menu">
               <li><a href="#">User settings</a></li>
               <li><%= link_to 'Log out', logout_path, :method => :delete  %></li>
             </ul>
           </li>
         <% else %>
           <li><%= link_to "Log in", login_path %></li>
           <li><%= link_to "Sign up", signup_path %></li>
         <% end %>
       </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Maintenance</title>
  <%= stylesheet_link_tag    "application", :media => "all", 
                          "data-turbolinks-track" => true%>
  <%= javascript_include_tag "application" , "data-turbolinks-track" => true%>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
 
  <div class="container">
    <% flash.each do | key, value | %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
	<%= render 'layouts/footer' %>
  <!--  <%= debug(params) if Rails.env.development? %>-->
  </div>
 
</body>
</html>